### ISSUE TITLE
YAML or automatic output_file?

### ISSUE THREAD

**Issue by mxmilkiib** [mb21/panrun#2]
How about making `panrun` simpler by being able to specify the output_file in the YAML front matter, or alternatively, using the same filename with the specified `output:` format?

**Comment by mb21** [comment]
The following should already work:

```
---
output:
  html:
    output: myfile.html
---
```

All params (including `output`) are simply forwarded to pandoc...

**Comment by mxmilkiib** [comment]
A-ha, thanks! I had tried putting `output: myfile.html` at the top and bottom of the header, but not indented/nested as your example there.

**Comment by mb21** [comment]
Sure, I updated the example in the README... https://github.com/mb21/panrun/commit/b4ef742c872b3ced14c4c999a0f62a0c42a707af

**Comment by mxmilkiib** [comment]
Thanks for your assistance. Might there a way for the following to work?

```
---
output:
  dzslides: 
    output: exercise.html
    self-contained: true
---

**Comment by mb21** [comment]
Yes, your example works for me. panrun outputs:

    panrun calling: pandoc input.md --output exercise.html --self-contained

and creates the file exercise.html.

**Comment by mxmilkiib** [comment]
The difference is that I'm now looking to output to the dzslides presentation format. To achieve this, I can run `panrun exercise.md -w dzslides`, which produces;

```
panrun calling: pandoc exercise.md --output exercise.html --self-contained -w dzslides
```

Though I'm wondering if it's possible to specify this in the config header.

**Comment by mb21** [comment]
Ah yes, the pandoc `-w` and `-t` options are shorthand for `--to`, so you can do it like with any other option:

```
---
output:
  dzslides:
    to: dzslides
    output: exercise.html
    self-contained: true
---
```
