### ISSUE TITLE
Using beamer

### ISSUE THREAD

**Issue by tomchor** [mb21/panrun#3]
Nice package!
But I couldn't make it work with the option `-t beamer`. 

I have the following template:

```
---
output:
  beamer_presentation:
classoption: "aspectratio=169"
---


Example slide
--------------------

Example slide
```

If I run it with `pandoc -t beamer slides.md -o slides.pdf` if works well. I can't put it in a way that `panrun` can understand though. Is this a limitation of `panrun`? Beamer slides are 80% of the reason why I'm starting to do use `panrun` so it would be awesome to make this work.

Thanks!

**Comment by mb21** [comment]
The panrun format for what you're trying to do is:

```
---
output:
  latex:
    to: beamer
    output: slides.pdf
classoption: "aspectratio=169"
---


Example slide
--------------------

Example slide
```

So thanks for reporting this, it provides already one data point against [panrun trying to be somewhat rmarkdown compatible](https://github.com/mb21/panrun/issues/1), since it confuses people probably more than it helps.

**Comment by tomchor** [comment]
Awesome. Worked like a charm. I was putting the `to: beamer` line outside of `latex:`.

Cheers!
